---
- hosts: localhost
  connection: local
  become: false 
  # This doesn't - the variable is undefined
  # become: "{{ False if ansible_pkg_mgr == 'brew' else True }}"
  # Nor does this - also undefined
  # become: "{{ False if ansible_os_family == 'Darwin' else True }}"

  tasks:
  - name: install network tools
    community.general.homebrew:
      name: iperf3
      state: present
      update_homebrew: yes

  - name: install general packages
    community.general.homebrew:
      name:  
#        - nally
        - iina
        - mcbopomofo  
        - blackhole-16ch
        - blackhole-2ch
        - openvpn-connect  
        - youtube-dl
        - qlmarkdown
        - ansible
      # - openvanilla # traditional chinese input

  - name: install applications
    community.general.homebrew:
      name: 
        - calibre
        - digikam
        - skype
        - eqmac
        - mcgimp
        - google-chrome

