---
- hosts: localhost
  connection: local
  become: false

  tasks:
  - name: install mac desktop by default
    package:
      name: 
        - macdown
        - macdown
        - macdown
        - macdown
